// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schedule.Models;

namespace Schedule.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181206152742_RoomToBuildMig")]
    partial class RoomToBuildMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Schedule.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("CountOfStoreys");

                    b.Property<byte>("Number");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Schedule.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Schedule.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("GroupId1");

                    b.Property<Guid?>("SubjectId1");

                    b.Property<Guid?>("TeacherId1");

                    b.HasKey("Id");

                    b.HasIndex("GroupId1");

                    b.HasIndex("SubjectId1");

                    b.HasIndex("TeacherId1");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Schedule.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BuildingId");

                    b.Property<int>("Number");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Schedule.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Schedule.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Schedule.Models.Lesson", b =>
                {
                    b.HasOne("Schedule.Models.Group")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupId1");

                    b.HasOne("Schedule.Models.Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId1");

                    b.HasOne("Schedule.Models.Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId1");
                });

            modelBuilder.Entity("Schedule.Models.Room", b =>
                {
                    b.HasOne("Schedule.Models.Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId");
                });
#pragma warning restore 612, 618
        }
    }
}
